
DELETE from BATCH_STEP_EXECUTION_CONTEXT ;
DELETE from  BATCH_JOB_EXECUTION_CONTEXT ;
DELETE from  BATCH_STEP_EXECUTION ;
DELETE from  BATCH_JOB_EXECUTION_PARAMS ;
DELETE from  BATCH_JOB_EXECUTION ;
DELETE from  BATCH_JOB_INSTANCE ;

-- 先删掉再重建 SEQUENCE，这样才能改变起始值
DROP SEQUENCE  BATCH_STEP_EXECUTION_SEQ ;
DROP SEQUENCE  BATCH_JOB_EXECUTION_SEQ ;
DROP SEQUENCE  BATCH_JOB_SEQ ;
CREATE SEQUENCE BATCH_STEP_EXECUTION_SEQ START WITH 0 MINVALUE 0 MAXVALUE 9223372036854775807 NOCYCLE;
CREATE SEQUENCE BATCH_JOB_EXECUTION_SEQ START WITH 0 MINVALUE 0 MAXVALUE 9223372036854775807 NOCYCLE;
CREATE SEQUENCE BATCH_JOB_SEQ START WITH 0 MINVALUE 0 MAXVALUE 9223372036854775807 NOCYCLE;