
CREATE TABLE PLAYERS (
	PLAYER_ID CHAR(8) NOT NULL PRIMARY KEY,
	LAST_NAME VARCHAR2(35) NOT NULL,
	FIRST_NAME VARCHAR2(25) NOT NULL,
	POS VARCHAR2(10) ,
	YEAR_OF_BIRTH NUMBER(38) NOT NULL,
	YEAR_DRAFTED NUMBER(38) NOT NULL
) ;


CREATE TABLE GAMES (
   PLAYER_ID CHAR(8) NOT NULL,
   YEAR_NO      NUMBER(38) NOT NULL,
   TEAM      CHAR(3) NOT NULL,
   WEEK      NUMBER(38) NOT NULL,
   OPPONENT  CHAR(3) ,
   COMPLETES NUMBER(38) ,
   ATTEMPTS  NUMBER(38) ,
   PASSING_YARDS NUMBER(38) ,
   PASSING_TD    NUMBER(38) ,
   INTERCEPTIONS NUMBER(38) ,
   RUSHES NUMBER(38) ,
   RUSH_YARDS NUMBER(38) ,
   RECEPTIONS NUMBER(38) ,
   RECEPTIONS_YARDS NUMBER(38) ,
   TOTAL_TD NUMBER(38)
) ;

CREATE TABLE PLAYER_SUMMARY  (
		  ID CHAR(8) NOT NULL,
		  YEAR_NO NUMBER(38) NOT NULL,
		  COMPLETES NUMBER(38) NOT NULL ,
		  ATTEMPTS NUMBER(38) NOT NULL ,
		  PASSING_YARDS NUMBER(38) NOT NULL ,
		  PASSING_TD NUMBER(38) NOT NULL ,
		  INTERCEPTIONS NUMBER(38) NOT NULL ,
		  RUSHES NUMBER(38) NOT NULL ,
		  RUSH_YARDS NUMBER(38) NOT NULL ,
		  RECEPTIONS NUMBER(38) NOT NULL ,
		  RECEPTIONS_YARDS NUMBER(38) NOT NULL ,
		  TOTAL_TD NUMBER(38) NOT NULL
) ;
