CREATE SEQUENCE BATCH_STAGING_SEQ START WITH 0 MINVALUE 0;
CREATE SEQUENCE TRADE_SEQ START WITH 0 MINVALUE 0;

CREATE TABLE BATCH_STAGING  (
	ID NUMBER(38)  NOT NULL PRIMARY KEY ,
	JOB_ID NUMBER(38) NOT NULL,
	VALUE BLOB NOT NULL,
	PROCESSED CHAR(1) NOT NULL
) ;