CREATE SEQUENCE TRADE_SEQ START WITH 0 MINVALUE 0;

CREATE TABLE TRADE  (
	ID NUMBER(38)  NOT NULL PRIMARY KEY ,
	VERSION NUMBER(38) ,
	ISIN VARCHAR(45) NOT NULL,
	QUANTITY NUMBER(38) ,
	PRICE DECIMAL(8,2) ,
	CUSTOMER VARCHAR2(45)
) ;